### ISSUE TITLE
Bug: Lara Climb.

### ISSUE THREAD

**Issue by Gh0stBlade** [XProger/OpenLara#38]
Level: LEVEL7A (Cistern)
Room: 111
Lara Position: 33453, -1580, 58468

Issue 1:
http://i.imgur.com/PRF6GMg.png
Pressing UP+Action will allow Lara to grab slope edges which isn't possible in the original game.

Issue 2:
http://i.imgur.com/r4iBYDO.png
Lara cannot jump up + hang to grab this wall. But if you climb on-top press back then grab. Lara can grab this wall which shouldn't be possible due to how low it is.

**Comment by hexdoll** [comment]
RE: Issue 6
I think the bug where Lara is unable to pull up in some places might be related to the edge she's hanging being on the boundary between two rooms.

**Comment by Gh0stBlade** [comment]
Another bug, similar to issue 1 which has been fixed.

LEVEL8A (City of Khamoon)
http://i.imgur.com/hoCXeP3.jpg
At the very beginning turn around. In reference to the screenshot position Lara there. If you hold the STEP RIGHT button, press ACTION then UP. Lara will vault on thin air.

**Comment by bryc** [comment]
![image](https://user-images.githubusercontent.com/1408749/51079958-35850800-16a0-11e9-80f4-1bb93ce9f8e0.png)

Still an issue I think - you can grab ledge from below bridge in map1 and even climb "downwards" into the floor. Easily reproducible many times, just jump and grab upward near middle bottom of bridge.

![image](https://user-images.githubusercontent.com/1408749/51079965-74b35900-16a0-11e9-977e-31451de1861b.png)

**Comment by dj4g11e32** [comment]
[Screencast 2020-08-28 20:38:01.zip](https://github.com/XProger/OpenLara/files/5144018/Screencast.2020-08-28.20.38.01.zip)
I've found another similar example in "City of Karmoon" where Lara can't pull up.  On the attached video, she can't pull up on the first two blocks where she stops, but can then pull up on the 3rd block. 

If someone could tell me how to get the coordinates to appear like in the screenshots by @Gh0stBlade, I'll be happy to add the info as I guess this would be more useful that the video.

**Comment by dj4g11e32** [comment]
> RE: Issue 6
> I think the bug where Lara is unable to pull up in some places might be related to the edge where she's hanging being on the boundary between two rooms.

I have an example that seems to back this up.  This screen-shot is in the Obelisk of Khamoon and is on the boundry between two 'rooms' (as defined in the Level editor).  Lara is unable to pull up onto the platform ahead of her even though there is plenty of space.

I'm running on Linux and have just run a git pull and built from source ('nix' version) to make sure I have all the latest fixes.

(I still can't work out how to find Lara's coordinates so I'll ask on the discord thread and post back here if I find out.)

![image](https://user-images.githubusercontent.com/10772935/91721713-1bf44500-eb91-11ea-83f3-6be463a685f8.png)

**Comment by XProger** [comment]
try to define _DEBUG in compiler options for onscreen info

**Comment by dj4g11e32** [comment]
> try to define _DEBUG in compiler options for onscreen info

I set the _DEBUG flag in build.sh but I get the following error when I try to build.
`../../debug.h:671:41: error: non-constant-expression cannot be narrowed from type 'unsigned long' to 'uint32' (aka 'unsigned int') in
      initializer list [-Wc++11-narrowing]
                        FOURCC("RIFF"), sizeof(Header) - 8 + dataSize,
`


I had a look through the debug.h file and can see the line that it refers to this but I don't know enough to help fix it...

Just FYI, my build.sh file now reads this (in case I made a mistake here):
`set -e
clang++ -std=c++11 -Os -s -fno-exceptions -fno-rtti -ffunction-sections -fdata-sections -Wl,--gc-sections -Wno-invalid-source-encoding -D_DEBUG -D_POSIX_THREADS -D_POSIX_READER_WRITER_LOCKS main.cpp ../../libs/stb_vorbis/stb_vorbis.c ../../libs/minimp3/minimp3.cpp ../../libs/tinf/tinflate.c -I../../ -o../../../bin/OpenLara_debug -lX11 -lGL -lm -lpthread -lpulse-simple -lpulse`
